services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - config:/config
      - cache:/cache
      - ./media:/media
    restart: always
    ports:
      - 8096:8096/tcp

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - jellyfin
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: always

volumes:
  config:
  cache:
